version: '3.8'
services:
  backend:
    build: ./packages/backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./packages/backend/src:/app/src
    depends_on:
      - redis
    environment:
      - NODE_ENV=development

  # Optional Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Embedding Worker Service
  embedding-worker:
    build: 
      context: ./packages/backend
    command: node src/worker/embedding-processor.js
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - EMBEDDING_BATCH_SIZE=10
    depends_on:
      - redis
      - backend
    volumes:
      - ./packages/backend/logs:/app/logs
    restart: unless-stopped

volumes:
  redis_data:
